openapi: 3.0.3

info:
  title: 'Dormitory system'
  version: 1.0.0

servers:
  - url: http://localhost:8183

tags:
  - name: Auth
    description: 'Methods for users authentication'
  - name: Bid
    description: 'Methods for working with user bids'
  - name: Dormitory
    description: 'Methods for working with dormitory entities'
  - name: File
    description: 'Methods for saving and getting files'

paths:
  /auth/register:
    $ref: './paths/auth.yaml#/register'
  /auth/login:
    $ref: './paths/auth.yaml#/login'
  /auth/register-other:
    $ref: './paths/auth.yaml#/register-other'
  /auth/change-password:
    $ref: './paths/auth.yaml#/change-password'
  /auth/profile:
    $ref: './paths/auth.yaml#/profile'

  /bid/my:
    $ref: './paths/bid.yaml#/my'
  /bid/my/opened-types:
    $ref: './paths/bid.yaml#/my~1opened-types'
  /bid/{id}:
    $ref: './paths/bid.yaml#/{id}'
  /bid/in-process:
    $ref: './paths/bid.yaml#/in-process'
  /bid/pending:
    $ref: './paths/bid.yaml#/pending'
  /bid/archived:
    $ref: './paths/bid.yaml#/archived'
  /bid/occupation:
    $ref: './paths/bid.yaml#/occupation'
  /bid/occupation/{id}:
    $ref: './paths/bid.yaml#/occupation~1{id}'
  /bid/eviction:
    $ref: './paths/bid.yaml#/eviction'
  /bid/eviction/{id}:
    $ref: './paths/bid.yaml#/eviction~1{id}'
  /bid/departure:
    $ref: './paths/bid.yaml#/departure'
  /bid/departure/{id}:
    $ref: './paths/bid.yaml#/departure~1{id}'
  /bid/room-change:
    $ref: './paths/bid.yaml#/room-change'
  /bid/room-change/{id}:
    $ref: './paths/bid.yaml#/room-change~1{id}'
  /bid/{id}/accept:
    $ref: './paths/bid.yaml#/{id}~1accept'
  /bid/{id}/pend:
    $ref: './paths/bid.yaml#/{id}~1pend'
  /bid/{id}/deny:
    $ref: './paths/bid.yaml#/{id}~1deny'

  /dormitory:
    $ref: './paths/dormitory.yaml#/root'
  /dormitory/{id}:
    $ref: './paths/dormitory.yaml#/{id}'

  /file/upload:
    $ref: './paths/file.yaml#/upload'
  /file/download/{key}:
    $ref: './paths/file.yaml#/download~1{key}'